#!/usr/bin/env node
/**
 * AVDE FreeLLMAPI Setup Script
 * ─────────────────────────────
 * Run once after cloning: node setup.mjs
 *
 * This script:
 *   1. Generates a .env with a fresh ENCRYPTION_KEY (if .env doesn't exist)
 *   2. Sets LOCAL_BYPASS=true (no API key needed for local calls)
 *   3. Sets LOCAL_PORT=3002 (no-auth loopback port for the backend)
 *   4. Installs npm dependencies (if node_modules is missing)
 *   5. Prints the startup command
 *
 * Token budget: FreeLLMAPI uses free providers (pollinations, kilo, llm7, ovh)
 * that give ~1.7B tokens/month shared across all teammates. No API key needed.
 */

import { randomBytes } from 'crypto';
import { existsSync, writeFileSync } from 'fs';
import { execSync } from 'child_process';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const envPath = join(__dirname, '.env');

// ── 1. Generate .env if it doesn't exist ─────────────────────────────────────
if (!existsSync(envPath)) {
  const key = randomBytes(32).toString('hex');
  const envContent = `# FreeLLMAPI configuration — auto-generated by setup.mjs
# DO NOT commit this file (it is gitignored for security)

# Server encryption key for API key storage
ENCRYPTION_KEY=${key}

# Server port (default: 3001) — backend calls http://127.0.0.1:3001/v1/
PORT=3001

# Allow loopback requests (127.0.0.1) to skip unified API key auth.
# Safe because only local processes can reach 127.0.0.1.
LOCAL_BYPASS=true

# Local-only no-auth port for the dashboard dev proxy
LOCAL_PORT=3002

# Token quota window (days). Free tier: ~1.7B tokens/month across team.
# Providers: pollinations, kilo, llm7, ovh — no API keys required.
REQUEST_ANALYTICS_RETENTION_DAYS=90
REQUEST_ANALYTICS_MAX_ROWS=100000
`;
  writeFileSync(envPath, envContent, 'utf8');
  console.log('✅ Created .env with fresh ENCRYPTION_KEY');
} else {
  console.log('ℹ️  .env already exists — skipping generation');
}

// ── 2. Install dependencies if needed ────────────────────────────────────────
const nodeModules = join(__dirname, 'node_modules');
if (!existsSync(nodeModules)) {
  console.log('📦 Installing npm dependencies...');
  execSync('npm install', { cwd: __dirname, stdio: 'inherit' });
  console.log('✅ Dependencies installed');
} else {
  console.log('ℹ️  node_modules already exists — skipping npm install');
}

// ── 3. Print startup info ─────────────────────────────────────────────────────
console.log(`
╔══════════════════════════════════════════════════════╗
║         AVDE FreeLLMAPI — Ready to Start             ║
╠══════════════════════════════════════════════════════╣
║  Start server:   npm run dev -w server               ║
║  API endpoint:   http://127.0.0.1:3001/v1/           ║
║  No-auth port:   http://127.0.0.1:3002/v1/ (local)  ║
║                                                      ║
║  Free token pool: ~1.7B tokens/month                 ║
║  Providers: pollinations, kilo, llm7, ovh            ║
║  No API key needed — just run and use!               ║
╚══════════════════════════════════════════════════════╝

Run to start:  cd llm/llm-proxy && npm run dev -w server
`);
